# Generated by Django 4.2.16 on 2026-05-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_account_is_primary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-is_primary", "-created_at"]},
        ),
    ]
