# Generated by Django 4.2.16 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_unique_type_per_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='account',
            name='unique_account_type_per_owner',
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(condition=models.Q(('account_type__in', ['CHECKING', 'BUSINESS', 'FIXED_TERM', 'CREDIT'])), fields=('owner', 'account_type'), name='unique_non_savings_account_type_per_owner'),
        ),
    ]
