# Generated by Django 4.2.16 on 2026-05-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_allow_multiple_savings_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_card_summary',
            field=models.BooleanField(default=False, help_text='Internal pooled account (e.g. savings goals pocket). Hidden from cards and account list.'),
        ),
    ]
