# Generated by Django 4.2.16 on 2026-05-03 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3)),
                ('to_currency', models.CharField(max_length=3)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=18)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('TRANSFER_LOCAL', 'Local Transfer'), ('TRANSFER_INTERNATIONAL', 'International Transfer'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('SERVICE_CHARGE', 'Service Charge')], max_length=40, unique=True)),
                ('flat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=4, default=0, help_text='e.g. 0.0150 = 1.5%', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, help_text='0 = no cap', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('TRANSFER_INTERNAL', 'Internal Transfer'), ('TRANSFER_EXTERNAL', 'External Transfer'), ('TRANSFER_INTERNATIONAL', 'International Transfer'), ('LOAN_DISBURSEMENT', 'Loan Disbursement'), ('LOAN_PAYMENT', 'Loan Payment'), ('FEE', 'Fee'), ('INTEREST', 'Interest'), ('REVERSAL', 'Reversal')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('FLAGGED', 'Flagged')], default='PENDING', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=8, default=1, max_digits=18)),
                ('idempotency_key', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('from_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='debits', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
