# Generated by Django 4.2.16 on 2026-05-13 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_compliance_regulated_session"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="regulatedtransfersession",
            new_name="transaction_user_id_768e58_idx",
            old_name="trans_reg_ses_user_status_idx",
        ),
        migrations.AlterField(
            model_name="transactionfee",
            name="charge_upfront",
            field=models.BooleanField(
                default=True,
                help_text="When true, fee is added on top of the principal (sender pays amount + fee). When false, fee is deducted from the recipient credit (same-currency transfers only).",
            ),
        ),
    ]
