# Generated by Django 4.2.16 on 2026-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0008_compliancefeeline_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancefeeline",
            name="code",
            field=models.SlugField(
                help_text="Stable key for reporting; unique per scope (global or user).",
                max_length=40,
            ),
        ),
    ]
