# Generated by Django 4.2.16 on 2026-05-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0011_regulatedtransfersession_compliance_scope"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulatedtransfersession",
            name="compliance_scope",
            field=models.CharField(
                choices=[("GLOBAL", "Global"), ("PERSONAL", "Personal (per user)")],
                default="GLOBAL",
                help_text="Fee pool frozen at session start: global lines only, or this user’s personal lines only.",
                max_length=20,
            ),
        ),
    ]
