# Generated by Django 4.2.16 on 2026-05-28 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0015_compliance_external_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regulatedtransfersessionline",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAYMENT_SUBMITTED", "Payment submitted"),
                    ("PAYMENT_CONFIRMED", "Payment confirmed"),
                    ("CHARGED", "OTP sent"),
                    ("OTP_VERIFIED", "OTP verified"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
