# Generated by Django 4.2.16 on 2026-05-03 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='statements/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_paperless', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounts.account')),
            ],
            options={
                'ordering': ['-period_end'],
                'unique_together': {('account', 'period_start', 'period_end')},
            },
        ),
    ]
