# Generated by Django 4.2.16 on 2026-05-21 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_account_exclude_from_card_summary"),
        ("users", "0004_emailotptoken_context_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="admin_account_scope",
            field=models.CharField(
                choices=[
                    ("ALL", "All accounts"),
                    ("SELECTED", "Selected accounts only"),
                ],
                default="ALL",
                help_text="Staff only: ALL = full bank desk; SELECTED = assigned accounts only.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id_document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PASSPORT", "International passport"),
                    ("DRIVERS_LICENSE", "Driver's license"),
                    ("RESIDENCE_PERMIT", "Residence permit"),
                    ("OTHER", "Other"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="StaffAccountAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_assignments",
                        to="accounts.account",
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="account_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="account_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assigned_at"],
                "unique_together": {("staff", "account")},
            },
        ),
    ]
