# Generated by Django 4.2.16 on 2026-05-03 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('term_months', models.PositiveIntegerField()),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAID_OFF', 'Paid Off'), ('DEFAULTED', 'Defaulted'), ('WRITTEN_OFF', 'Written Off')], default='ACTIVE', max_length=20)),
                ('disbursed_at', models.DateTimeField(blank=True, null=True)),
                ('next_payment_due', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('term_months', models.PositiveIntegerField()),
                ('purpose', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISBURSED', 'Disbursed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('MORTGAGE', 'Mortgage / Home Loan'), ('AUTO', 'Auto Loan'), ('BUSINESS', 'Business Loan'), ('EDUCATION', 'Education Loan')], max_length=20)),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual rate, e.g. 0.1200 = 12%', max_digits=5)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('min_term_months', models.PositiveIntegerField(default=1)),
                ('max_term_months', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('installment_number', models.PositiveIntegerField()),
                ('due_date', models.DateField()),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('interest_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('loan_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='loans.loanaccount')),
            ],
            options={
                'ordering': ['installment_number'],
            },
        ),
    ]
