# Generated by Django 4.2.16 on 2026-05-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0004_loanproduct_marketing_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanproduct",
            name="description",
            field=models.TextField(
                blank=True, help_text="Short summary on loan cards."
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="full_description",
            field=models.TextField(
                blank=True,
                help_text="Long-form copy shown in the product detail modal.",
            ),
        ),
        migrations.AlterField(
            model_name="loanproduct",
            name="tagline",
            field=models.CharField(
                blank=True,
                help_text="One-line pitch in the product modal header.",
                max_length=280,
            ),
        ),
    ]
