# Generated by Django 4.2.16 on 2026-05-03 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('FAILED_LOGIN', 'Failed Login'), ('TRANSACTION', 'Transaction'), ('REVERSAL', 'Reversal'), ('FREEZE_ACCOUNT', 'Freeze Account'), ('CLOSE_ACCOUNT', 'Close Account'), ('ROLE_CHANGE', 'Role Change'), ('KYC_UPDATE', 'KYC Update'), ('LOAN_DECISION', 'Loan Decision'), ('CONFIG_CHANGE', 'Config Change'), ('VIEW_SENSITIVE', 'View Sensitive Data')], max_length=30)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.CharField(blank=True, max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
