# Generated by Django 4.2.16 on 2026-05-03 14:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('TRANSACTION', 'Transaction'), ('LOW_BALANCE', 'Low Balance'), ('LOAN_APPROVED', 'Loan Approved'), ('LOAN_REJECTED', 'Loan Rejected'), ('LOAN_PAYMENT_DUE', 'Loan Payment Due'), ('PASSWORD_RESET', 'Password Reset'), ('MFA_OTP', 'MFA OTP'), ('REGISTRATION', 'Registration'), ('STATEMENT_READY', 'Statement Ready'), ('SUPPORT_UPDATE', 'Support Update'), ('SECURITY_ALERT', 'Security Alert')], max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('email_status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_alerts', models.BooleanField(default=True)),
                ('low_balance_alerts', models.BooleanField(default=True)),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=100, max_digits=10)),
                ('loan_alerts', models.BooleanField(default=True)),
                ('security_alerts', models.BooleanField(default=True)),
                ('statement_alerts', models.BooleanField(default=True)),
            ],
        ),
    ]
