# Generated by Django 4.2.16 on 2026-05-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_profile_update_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("TRANSACTION", "Transaction"),
                    ("LOW_BALANCE", "Low Balance"),
                    ("LOAN_APPROVED", "Loan Approved"),
                    ("LOAN_REJECTED", "Loan Rejected"),
                    ("LOAN_PAYMENT_DUE", "Loan Payment Due"),
                    ("PASSWORD_RESET", "Password Reset"),
                    ("MFA_OTP", "MFA OTP"),
                    ("REGISTRATION", "Registration"),
                    ("STATEMENT_READY", "Statement Ready"),
                    ("SUPPORT_UPDATE", "Support Update"),
                    ("SECURITY_ALERT", "Security Alert"),
                    ("PROFILE_UPDATE_APPROVED", "Profile update approved"),
                    ("GOAL_AUTOSAVE_SUCCESS", "Goal autosave contribution"),
                    ("GOAL_AUTOSAVE_INSUFFICIENT", "Goal autosave insufficient funds"),
                ],
                max_length=30,
            ),
        ),
    ]
